services:
   mongodb:
      image: mongo:7
      container_name: recepcion-app-db
      restart: always
      ports:
         - '27017:27017'
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
         MONGO_INITDB_DATABASE: ${MONGO_DB}
      volumes:
         - mongo_data:/data/db

   backend:
      build:
         context: .
         dockerfile: deploy/Dockerfile
      container_name: recepcion-backend
      restart: always
      ports:
         - '8081:8081'
      env_file:
         - .env.production
      environment:
         DATABASE_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@recepcion-app-db:27017/${MONGO_DB}?authSource=admin
         PRINTER_IP: ${PRINTER_IP:-192.168.1.43}
         PRINTER_PORT: ${PRINTER_PORT:-9100}
      depends_on:
         - mongodb
      extra_hosts:
         - 'host.docker.internal:host-gateway'

volumes:
   mongo_data:
